# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 04:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id_aud', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('results', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id_com', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('attorney', models.CharField(blank=True, max_length=45, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('fax', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('ein', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('logo', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('unity', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('deactivate', models.IntegerField(blank=True, null=True)),
                ('deactivate_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id_con', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('serial', models.CharField(blank=True, max_length=20, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Customers')),
            ],
        ),
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('id_drv', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('license_numb', models.CharField(blank=True, max_length=45, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('lic_date_exp', models.DateField(blank=True, null=True)),
                ('medicard_date_exp', models.DateField(blank=True, null=True)),
                ('drugtest_date', models.DateField(blank=True, null=True)),
                ('drugtest_date_exp', models.DateField(blank=True, null=True)),
                ('mbr_date', models.DateField(blank=True, null=True)),
                ('mbr_date_exp', models.DateField(blank=True, null=True)),
                ('begining_date', models.DateField(blank=True, null=True)),
                ('deactivate', models.IntegerField(blank=True, null=True)),
                ('deactivate_date', models.DateField(blank=True, null=True)),
                ('companies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Companies')),
            ],
        ),
        migrations.CreateModel(
            name='Ifta',
            fields=[
                ('id_ift', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=45, null=True)),
                ('milles', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('gallons', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('customers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Customers')),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id_ins', models.AutoField(primary_key=True, serialize=False)),
                ('down_payment', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('pilicy_efective_date', models.DateField(blank=True, null=True)),
                ('pilicy_date_exp', models.DateField(blank=True, null=True)),
                ('liability', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('pilicy_liability', models.CharField(blank=True, max_length=45, null=True)),
                ('cargo', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('cargo_pilicy', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('physical_damage', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('physical_damg_pilicy', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('sale_type', models.CharField(blank=True, max_length=20, null=True)),
                ('sale_date_fee', models.DateField(blank=True, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('comision', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('paid', models.IntegerField(blank=True, null=True)),
                ('accounts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Accounts')),
                ('companies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Companies')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id_mnt', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.CharField(blank=True, max_length=255, null=True)),
                ('companies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Companies')),
                ('contracts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Contracts')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id_per', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('usdot', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('usdot_pin', models.CharField(blank=True, max_length=20, null=True)),
                ('txdmv', models.CharField(blank=True, max_length=20, null=True)),
                ('txdmv_user', models.CharField(blank=True, max_length=20, null=True)),
                ('txdmv_passd', models.CharField(blank=True, max_length=45, null=True)),
                ('txdmv_date', models.DateField(blank=True, null=True)),
                ('txdmv_date_exp', models.DateField(blank=True, null=True)),
                ('mc', models.CharField(blank=True, max_length=20, null=True)),
                ('mc_pin', models.CharField(blank=True, max_length=20, null=True)),
                ('boc3', models.IntegerField(blank=True, null=True)),
                ('boc3_date', models.DateField(blank=True, null=True)),
                ('ucr', models.IntegerField(blank=True, null=True)),
                ('update', models.DateField(blank=True, null=True)),
                ('companies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Companies')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trucks',
            fields=[
                ('id_tru', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=45, null=True)),
                ('year', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('model', models.CharField(blank=True, max_length=45, null=True)),
                ('serial', models.CharField(blank=True, max_length=20, null=True)),
                ('number', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('insp_date_exp', models.DateField(blank=True, null=True)),
                ('regit_date_exp', models.DateField(blank=True, null=True)),
                ('deactivate', models.IntegerField(blank=True, null=True)),
                ('deactivate_date', models.DateField(blank=True, null=True)),
                ('companies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Companies')),
            ],
        ),
        migrations.AddField(
            model_name='ifta',
            name='trucks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Trucks'),
        ),
        migrations.AddField(
            model_name='ifta',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
