# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id_aud', models.AutoField(primary_key=True, serialize=False)),
                ('type_aud', models.CharField(blank=True, max_length=20, null=True)),
                ('date_aud', models.DateField(blank=True, null=True)),
                ('results_aud', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id_com', models.AutoField(primary_key=True, serialize=False)),
                ('name_com', models.CharField(blank=True, max_length=45, null=True)),
                ('attorney_com', models.CharField(blank=True, max_length=45, null=True)),
                ('address_com', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_com', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('fax_com', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('ein_com', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('logo_com', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date_com', models.DateField(blank=True, null=True)),
                ('unity_com', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('deactivate_com', models.IntegerField(blank=True, null=True)),
                ('deactivate_date_com', models.DateField(blank=True, null=True)),
                ('customers', models.ForeignKey(db_column='CUSTOMERS_id_cut', on_delete=django.db.models.deletion.DO_NOTHING, to='accounting.Customers')),
                ('folders', models.ForeignKey(db_column='FOLDERS_id_fld', on_delete=django.db.models.deletion.DO_NOTHING, to='administration.Folders')),
                ('users', models.ForeignKey(db_column='USERS_id_use', on_delete=django.db.models.deletion.DO_NOTHING, to='administration.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id_con', models.AutoField(primary_key=True, serialize=False)),
                ('description_con', models.CharField(blank=True, max_length=255, null=True)),
                ('serial_con', models.CharField(blank=True, max_length=20, null=True)),
                ('start_date_con', models.DateField(blank=True, null=True)),
                ('end_date_con', models.DateField(blank=True, null=True)),
                ('type_con', models.CharField(blank=True, max_length=20, null=True)),
                ('customer', models.ForeignKey(db_column='CUSTOMERS_id_cut', on_delete=django.db.models.deletion.DO_NOTHING, to='accounting.Customers')),
                ('files', models.ForeignKey(db_column='FILES_id_fil', on_delete=django.db.models.deletion.DO_NOTHING, to='administration.Files')),
                ('users', models.ForeignKey(db_column='USERS_id_use', on_delete=django.db.models.deletion.DO_NOTHING, to='administration.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('id_drv', models.AutoField(primary_key=True, serialize=False)),
                ('name_drv', models.CharField(blank=True, max_length=45, null=True)),
                ('license_numb_drv', models.CharField(blank=True, max_length=45, null=True)),
                ('address_drv', models.CharField(blank=True, max_length=255, null=True)),
                ('dob_drv', models.DateField(blank=True, null=True)),
                ('lic_date_exp_drv', models.DateField(blank=True, null=True)),
                ('medicard_date_exp_drv', models.DateField(blank=True, null=True)),
                ('drugtest_date_drv', models.DateField(blank=True, null=True)),
                ('drugtest_date_exp_drv', models.DateField(blank=True, null=True)),
                ('mbr_date_drv', models.DateField(blank=True, null=True)),
                ('mbr_date_exp_drv', models.DateField(blank=True, null=True)),
                ('begining_date_drv', models.DateField(blank=True, null=True)),
                ('deactivate_drv', models.IntegerField(blank=True, null=True)),
                ('deactivate_date_drv', models.DateField(blank=True, null=True)),
                ('companies', models.ForeignKey(db_column='COMPANIES_id_com', on_delete=django.db.models.deletion.DO_NOTHING, to='services.Companies')),
            ],
        ),
        migrations.CreateModel(
            name='Ifta',
            fields=[
                ('id_ift', models.AutoField(primary_key=True, serialize=False)),
                ('date_ift', models.DateField(blank=True, null=True)),
                ('state_ift', models.CharField(blank=True, max_length=45, null=True)),
                ('milles_ift', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('gallons_ift', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('customers', models.ForeignKey(db_column='CUSTOMERS_id_cut', on_delete=django.db.models.deletion.DO_NOTHING, to='accounting.Customers')),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id_ins', models.AutoField(primary_key=True, serialize=False)),
                ('down_payment_ins', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('pilicy_efective_date_ins', models.DateField(blank=True, null=True)),
                ('pilicy_date_exp_ins', models.DateField(blank=True, null=True)),
                ('liability_ins', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('pilicy_liability_ins', models.CharField(blank=True, max_length=45, null=True)),
                ('cargo_ins', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('cargo_pilicy_ins', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('physical_damage_ins', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('physical_damg_pilicy_ins', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('sale_type_ins', models.CharField(blank=True, max_length=20, null=True)),
                ('sale_date_fee_ins', models.DateField(blank=True, null=True)),
                ('total_ins', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('comision_ins', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('paid_ins', models.IntegerField(blank=True, null=True)),
                ('accounts', models.ForeignKey(db_column='ACCOUNTS_id_acn', on_delete=django.db.models.deletion.DO_NOTHING, to='accounting.Accounts')),
                ('companies', models.ForeignKey(db_column='COMPANIES_id_com', on_delete=django.db.models.deletion.DO_NOTHING, to='services.Companies')),
                ('users', models.ForeignKey(db_column='USERS_id_use', on_delete=django.db.models.deletion.DO_NOTHING, to='administration.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id_mnt', models.AutoField(primary_key=True, serialize=False)),
                ('nota_mnt', models.CharField(blank=True, max_length=255, null=True)),
                ('companies', models.ForeignKey(db_column='COMPANIES_id_com', on_delete=django.db.models.deletion.DO_NOTHING, to='services.Companies')),
                ('contracts', models.ForeignKey(db_column='CONTRACTS_id_con', on_delete=django.db.models.deletion.DO_NOTHING, to='services.Contracts')),
                ('users', models.ForeignKey(db_column='USERS_id_use', on_delete=django.db.models.deletion.DO_NOTHING, to='administration.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id_per', models.AutoField(primary_key=True, serialize=False)),
                ('date_per', models.DateField(blank=True, null=True)),
                ('usdot_per', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('usdot_pin_per', models.CharField(blank=True, max_length=20, null=True)),
                ('txdmv_per', models.CharField(blank=True, max_length=20, null=True)),
                ('txdmv_user_per', models.CharField(blank=True, max_length=20, null=True)),
                ('txdmv_passd_per', models.CharField(blank=True, max_length=45, null=True)),
                ('txdmv_date_per', models.DateField(blank=True, null=True)),
                ('txdmv_date_exp_per', models.DateField(blank=True, null=True)),
                ('mc_per', models.CharField(blank=True, max_length=20, null=True)),
                ('mc_pin_per', models.CharField(blank=True, max_length=20, null=True)),
                ('boc3_per', models.IntegerField(blank=True, null=True)),
                ('boc3_date_per', models.DateField(blank=True, null=True)),
                ('ucr_per', models.IntegerField(blank=True, null=True)),
                ('update_per', models.DateField(blank=True, null=True)),
                ('companies', models.ForeignKey(db_column='COMPANIES_id_com', on_delete=django.db.models.deletion.DO_NOTHING, to='services.Companies')),
                ('users', models.ForeignKey(db_column='USERS_id_use', on_delete=django.db.models.deletion.DO_NOTHING, to='administration.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Trucks',
            fields=[
                ('id_tru', models.AutoField(primary_key=True, serialize=False)),
                ('type_tru', models.CharField(blank=True, max_length=45, null=True)),
                ('year_tru', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('model_tru', models.CharField(blank=True, max_length=45, null=True)),
                ('serial_tru', models.CharField(blank=True, max_length=20, null=True)),
                ('number_tru', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('insp_date_exp_tru', models.DateField(blank=True, null=True)),
                ('regit_date_exp_tru', models.DateField(blank=True, null=True)),
                ('deactivate_tru', models.IntegerField(blank=True, null=True)),
                ('deactivate_date_tru', models.DateField(blank=True, null=True)),
                ('companies', models.ForeignKey(db_column='COMPANIES_id_com', on_delete=django.db.models.deletion.DO_NOTHING, to='services.Companies')),
            ],
        ),
        migrations.AddField(
            model_name='ifta',
            name='trucks',
            field=models.ForeignKey(db_column='TRUCKS_id_tru', on_delete=django.db.models.deletion.DO_NOTHING, to='services.Trucks'),
        ),
        migrations.AddField(
            model_name='ifta',
            name='users',
            field=models.ForeignKey(db_column='USERS_id_use', on_delete=django.db.models.deletion.DO_NOTHING, to='administration.Users'),
        ),
        migrations.AddField(
            model_name='audit',
            name='companies',
            field=models.ForeignKey(db_column='COMPANIES_id_com', on_delete=django.db.models.deletion.DO_NOTHING, to='services.Companies'),
        ),
        migrations.AddField(
            model_name='audit',
            name='contracts',
            field=models.ForeignKey(db_column='CONTRACTS_id_con', on_delete=django.db.models.deletion.DO_NOTHING, to='services.Contracts'),
        ),
        migrations.AddField(
            model_name='audit',
            name='folders',
            field=models.ForeignKey(db_column='FOLDERS_id_fld', on_delete=django.db.models.deletion.DO_NOTHING, to='administration.Folders'),
        ),
        migrations.AddField(
            model_name='audit',
            name='users',
            field=models.ForeignKey(db_column='USERS_id_use', on_delete=django.db.models.deletion.DO_NOTHING, to='administration.Users'),
        ),
    ]
