# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 23:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='companies',
            field=models.ForeignKey(db_column='COMPANIES_id_com', on_delete=django.db.models.deletion.CASCADE, to='services.Companies'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='contracts',
            field=models.ForeignKey(db_column='CONTRACTS_id_con', on_delete=django.db.models.deletion.CASCADE, to='services.Contracts'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='folders',
            field=models.ForeignKey(db_column='FOLDERS_id_fld', on_delete=django.db.models.deletion.CASCADE, to='administration.Folders'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='users',
            field=models.ForeignKey(db_column='USERS_id_use', on_delete=django.db.models.deletion.CASCADE, to='administration.Users'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='customers',
            field=models.ForeignKey(db_column='CUSTOMERS_id_cut', on_delete=django.db.models.deletion.CASCADE, to='accounting.Customers'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='folders',
            field=models.ForeignKey(db_column='FOLDERS_id_fld', on_delete=django.db.models.deletion.CASCADE, to='administration.Folders'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='users',
            field=models.ForeignKey(db_column='USERS_id_use', on_delete=django.db.models.deletion.CASCADE, to='administration.Users'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='customer',
            field=models.ForeignKey(db_column='CUSTOMERS_id_cut', on_delete=django.db.models.deletion.CASCADE, to='accounting.Customers'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='files',
            field=models.ForeignKey(db_column='FILES_id_fil', on_delete=django.db.models.deletion.CASCADE, to='administration.Files'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='users',
            field=models.ForeignKey(db_column='USERS_id_use', on_delete=django.db.models.deletion.CASCADE, to='administration.Users'),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='companies',
            field=models.ForeignKey(db_column='COMPANIES_id_com', on_delete=django.db.models.deletion.CASCADE, to='services.Companies'),
        ),
        migrations.AlterField(
            model_name='ifta',
            name='customers',
            field=models.ForeignKey(db_column='CUSTOMERS_id_cut', on_delete=django.db.models.deletion.CASCADE, to='accounting.Customers'),
        ),
        migrations.AlterField(
            model_name='ifta',
            name='trucks',
            field=models.ForeignKey(db_column='TRUCKS_id_tru', on_delete=django.db.models.deletion.CASCADE, to='services.Trucks'),
        ),
        migrations.AlterField(
            model_name='ifta',
            name='users',
            field=models.ForeignKey(db_column='USERS_id_use', on_delete=django.db.models.deletion.CASCADE, to='administration.Users'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='accounts',
            field=models.ForeignKey(db_column='ACCOUNTS_id_acn', on_delete=django.db.models.deletion.CASCADE, to='accounting.Accounts'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='companies',
            field=models.ForeignKey(db_column='COMPANIES_id_com', on_delete=django.db.models.deletion.CASCADE, to='services.Companies'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='users',
            field=models.ForeignKey(db_column='USERS_id_use', on_delete=django.db.models.deletion.CASCADE, to='administration.Users'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='companies',
            field=models.ForeignKey(db_column='COMPANIES_id_com', on_delete=django.db.models.deletion.CASCADE, to='services.Companies'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='contracts',
            field=models.ForeignKey(db_column='CONTRACTS_id_con', on_delete=django.db.models.deletion.CASCADE, to='services.Contracts'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='users',
            field=models.ForeignKey(db_column='USERS_id_use', on_delete=django.db.models.deletion.CASCADE, to='administration.Users'),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='companies',
            field=models.ForeignKey(db_column='COMPANIES_id_com', on_delete=django.db.models.deletion.CASCADE, to='services.Companies'),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='users',
            field=models.ForeignKey(db_column='USERS_id_use', on_delete=django.db.models.deletion.CASCADE, to='administration.Users'),
        ),
        migrations.AlterField(
            model_name='trucks',
            name='companies',
            field=models.ForeignKey(db_column='COMPANIES_id_com', on_delete=django.db.models.deletion.CASCADE, to='services.Companies'),
        ),
    ]
