# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 04:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0002_auto_20170509_2351'),
        ('tools', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracts',
            name='files',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.Files'),
        ),
        migrations.AddField(
            model_name='contracts',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companies',
            name='customers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Customers'),
        ),
        migrations.AddField(
            model_name='companies',
            name='folders',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.Folders'),
        ),
        migrations.AddField(
            model_name='companies',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='audit',
            name='companies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Companies'),
        ),
        migrations.AddField(
            model_name='audit',
            name='contracts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Contracts'),
        ),
        migrations.AddField(
            model_name='audit',
            name='folders',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.Folders'),
        ),
        migrations.AddField(
            model_name='audit',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
