# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 15:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0002_auto_20170625_0051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id_plt', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('date_exp', models.DateField(blank=True, null=True)),
                ('account_number', models.CharField(blank=True, max_length=45, null=True)),
                ('account_user', models.CharField(blank=True, max_length=45, null=True)),
                ('account_password', models.CharField(blank=True, max_length=45, null=True)),
                ('customers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Customer')),
                ('trucks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Trucks')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id_tle', models.AutoField(primary_key=True, serialize=False)),
                ('date_reg', models.DateField(blank=True, null=True)),
                ('date_exp_reg', models.DateField(blank=True, null=True)),
                ('date_insp', models.DateField(blank=True, null=True)),
                ('date_exp_insp', models.DateField(blank=True, null=True)),
                ('customers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Customer')),
                ('trucks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Trucks')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
