# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 15:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0003_plate_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id_apl', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('fullname', models.CharField(max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('no_social', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(max_length=255)),
                ('license_numb', models.CharField(blank=True, max_length=45, null=True)),
                ('usdot', models.IntegerField(blank=True, null=True)),
                ('mc', models.IntegerField(blank=True, null=True)),
                ('txdmv', models.IntegerField(blank=True, null=True)),
                ('ein', models.IntegerField(blank=True, null=True)),
                ('service', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('date_view', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
