# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_auto_20170808_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='companie',
            name='otheattorney',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='companie',
            name='othephone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
