# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-20 20:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0007_auto_20170820_1530'),
        ('services', '0010_auto_20170810_0133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id_tru', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=45, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('model', models.CharField(blank=True, max_length=45, null=True)),
                ('serial', models.CharField(blank=True, max_length=20, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('plate_date_exp', models.DateField(blank=True, null=True)),
                ('plate_account_number', models.CharField(blank=True, max_length=45, null=True)),
                ('plate_account_user', models.CharField(blank=True, max_length=45, null=True)),
                ('plate_account_password', models.CharField(blank=True, max_length=45, null=True)),
                ('title_date_reg', models.DateField(blank=True, null=True)),
                ('title_date_exp_reg', models.DateField(blank=True, null=True)),
                ('title_date_insp', models.DateField(blank=True, null=True)),
                ('title_date_exp_insp', models.DateField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('update', models.DateField(blank=True, null=True)),
                ('deactivate', models.BooleanField(default=False)),
                ('deactivate_date', models.DateField(blank=True, null=True)),
                ('customers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id_com', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('attorney', models.CharField(blank=True, max_length=45, null=True)),
                ('otheattorney', models.CharField(blank=True, max_length=45, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('othephone', models.CharField(blank=True, max_length=10, null=True)),
                ('fax', models.CharField(blank=True, max_length=10, null=True)),
                ('ein', models.CharField(blank=True, max_length=20, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('created_date', models.DateField(blank=True, null=True)),
                ('unit', models.IntegerField(blank=True, null=True)),
                ('usdot', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('usdot_pin', models.CharField(blank=True, max_length=20, null=True)),
                ('txdmv', models.CharField(blank=True, max_length=20, null=True)),
                ('txdmv_user', models.CharField(blank=True, max_length=20, null=True)),
                ('txdmv_passd', models.CharField(blank=True, max_length=45, null=True)),
                ('txdmv_date', models.DateField(blank=True, null=True)),
                ('txdmv_date_exp', models.DateField(blank=True, null=True)),
                ('mc', models.CharField(blank=True, max_length=20, null=True)),
                ('mc_pin', models.CharField(blank=True, max_length=20, null=True)),
                ('boc3', models.IntegerField(blank=True, null=True)),
                ('boc3_date', models.DateField(blank=True, null=True)),
                ('ucr', models.IntegerField(blank=True, null=True)),
                ('ucr_date_exp', models.DateField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('update', models.DateField(blank=True, null=True)),
                ('deactivate', models.BooleanField(default=False)),
                ('deactivate_date', models.DateField(blank=True, null=True)),
                ('customers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Customer')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
