# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-20 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_auto_20170820_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='balance_due',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='paid_out',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
