# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-21 04:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_auto_20170820_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='customer',
            new_name='customers',
        ),
    ]
