# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-21 07:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_auto_20170820_2319'),
        ('services', '0011_merge_20170810_0706'),
    ]

    operations = [
    ]
