# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-30 05:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_auto_20170829_1843'),
        ('services', '0015_merge_20170821_0713'),
    ]

    operations = [
    ]
