# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-15 04:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_auto_20170914_2351'),
        ('services', '0016_merge_20170830_0544'),
    ]

    operations = [
    ]
