# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-16 02:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_auto_20170914_2351'),
        ('services', '0015_merge_20170822_2123'),
    ]

    operations = [
    ]
