# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-19 04:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_merge_20170915_2156'),
        ('services', '0017_merge_20170915_0455'),
    ]

    operations = [
    ]
