# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-22 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_merge_20170915_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='plate_account_number',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='plate_account_password',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='plate_account_user',
        ),
        migrations.AddField(
            model_name='ifta',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ifta',
            name='payment_due',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='monthlypay',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='note',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='permit',
            name='account_number',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='permit',
            name='account_password',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='permit',
            name='account_user',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='permit',
            name='inter',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='permit',
            name='boc3',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='permit',
            name='ucr',
            field=models.BooleanField(default=False),
        ),
    ]
