# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_auto_20171022_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='cargo_policy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='physical_damg_policy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='policy_liability',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
