# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-22 22:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_auto_20171022_1557'),
        ('services', '0018_merge_20170919_0418'),
    ]

    operations = [
    ]
