# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-30 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_auto_20171111_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companie',
            name='customers',
        ),
        migrations.RemoveField(
            model_name='companie',
            name='folders',
        ),
        migrations.RemoveField(
            model_name='companie',
            name='users',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='contracts',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='customers',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='users',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='customers',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='users',
        ),
        migrations.RemoveField(
            model_name='plate',
            name='customers',
        ),
        migrations.RemoveField(
            model_name='plate',
            name='trucks',
        ),
        migrations.RemoveField(
            model_name='plate',
            name='users',
        ),
        migrations.RemoveField(
            model_name='title',
            name='customers',
        ),
        migrations.RemoveField(
            model_name='title',
            name='trucks',
        ),
        migrations.RemoveField(
            model_name='title',
            name='users',
        ),
        migrations.RemoveField(
            model_name='trucks',
            name='companies',
        ),
        migrations.AddField(
            model_name='insurance',
            name='other',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='other_description',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='other_policy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='policy_cargo_exp',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='policy_other_exp',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='policy_physical_exp',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Companie',
        ),
        migrations.DeleteModel(
            name='Maintenance',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.DeleteModel(
            name='Plate',
        ),
        migrations.DeleteModel(
            name='Title',
        ),
        migrations.DeleteModel(
            name='Trucks',
        ),
    ]
