# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='allDay',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
