# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='url',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
