# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 03:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_auto_20170518_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busines',
            name='fax',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='busines',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='folder',
            name='folders_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tools.Folder'),
        ),
    ]
