# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('tools', '0002_auto_20170623_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='group',
        ),
        migrations.AddField(
            model_name='alert',
            name='group',
            field=models.ManyToManyField(blank=True, null=True, to='auth.Group'),
        ),
    ]
