# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_auto_20170709_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='date_save',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
