# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_auto_20170709_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busines',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
