# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-21 21:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_auto_20170709_2318'),
        ('tools', '0007_auto_20170710_0151'),
    ]

    operations = [
    ]
