# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0007_auto_20170710_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='directory',
            name='name',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='directory',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='file',
            name='url',
            field=models.FileField(blank=True, null=True, upload_to='Forms/'),
        ),
    ]
