# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 13:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0008_auto_20170723_1821'),
        ('tools', '0008_auto_20170724_1259'),
    ]

    operations = [
    ]
