# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-26 03:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0008_merge_20170721_1645'),
        ('tools', '0008_auto_20170723_1821'),
    ]

    operations = [
    ]
