# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-05 23:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0008_auto_20170723_1821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='drescription',
            new_name='category',
        ),
    ]
