# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-06 20:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0009_merge_20170724_1307'),
        ('tools', '0009_auto_20170805_1842'),
    ]

    operations = [
    ]
