# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriversLogt',
            fields=[
                ('id_dr', models.AutoField(primary_key=True, serialize=False)),
                ('name_dr', models.CharField(blank=True, max_length=45, null=True)),
                ('license_numb_dr', models.CharField(blank=True, max_length=45, null=True)),
                ('address_dr', models.CharField(blank=True, max_length=255, null=True)),
                ('dob_dr', models.DateField(blank=True, null=True)),
                ('lic_date_exp_dr', models.DateField(blank=True, null=True)),
                ('medicard_date_exp_dr', models.DateField(blank=True, null=True)),
                ('drugtest_date_dr', models.DateField(blank=True, null=True)),
                ('drugtest_date_exp_dr', models.DateField(blank=True, null=True)),
                ('mbr_date_dr', models.DateField(blank=True, null=True)),
                ('mbr_date_exp_dr', models.DateField(blank=True, null=True)),
                ('begining_date_dr', models.DateField(blank=True, null=True)),
                ('deactivate_dr', models.IntegerField(blank=True, null=True)),
                ('deactivate_date_dr', models.DateField(blank=True, null=True)),
                ('active_dr', models.IntegerField()),
                ('date_deactivated_dr', models.DateTimeField(blank=True, null=True)),
                ('users_id_use', models.ForeignKey(db_column='USERS_id_use', on_delete=django.db.models.deletion.DO_NOTHING, to='administration.Users')),
            ],
        ),
        migrations.CreateModel(
            name='IftaLogt',
            fields=[
                ('id_ift', models.AutoField(primary_key=True, serialize=False)),
                ('date_ift', models.DateField(blank=True, null=True)),
                ('state_ift', models.CharField(blank=True, max_length=45, null=True)),
                ('milles_ift', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('gallons_ift', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('customers', models.ForeignKey(db_column='CUSTOMERS_id_cut', on_delete=django.db.models.deletion.DO_NOTHING, to='accounting.Customers')),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceLogt',
            fields=[
                ('id_inr', models.AutoField(primary_key=True, serialize=False)),
                ('down_payment_inr', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('pilicy_efective_date_inr', models.DateField(blank=True, null=True)),
                ('pilicy_date_exp_inr', models.DateField(blank=True, null=True)),
                ('liability_inr', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('pilicy_liability_inr', models.CharField(blank=True, max_length=45, null=True)),
                ('cargo_inr', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('cargo_pilicy_inr', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('physical_damage_inr', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('physical_damg_pilicy_inr', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('sale_type_inr', models.CharField(blank=True, max_length=20, null=True)),
                ('sale_date_fee_inr', models.DateField(blank=True, null=True)),
                ('total_inr', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('comision_inr', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('paid_inr', models.IntegerField(blank=True, null=True)),
                ('accounts', models.ForeignKey(db_column='ACCOUNTS_id_acn', on_delete=django.db.models.deletion.DO_NOTHING, to='accounting.Accounts')),
                ('users', models.ForeignKey(db_column='USERS_id_use', on_delete=django.db.models.deletion.DO_NOTHING, to='administration.Users')),
            ],
        ),
        migrations.CreateModel(
            name='InvoicesHasLoads',
            fields=[
                ('id_inl', models.AutoField(primary_key=True, serialize=False)),
                ('invoices', models.ForeignKey(db_column='INVOICES_id_inv', on_delete=django.db.models.deletion.DO_NOTHING, to='accounting.Invoices')),
            ],
        ),
        migrations.CreateModel(
            name='Loads',
            fields=[
                ('id_lod', models.AutoField(primary_key=True, serialize=False)),
                ('broker_lod', models.CharField(blank=True, max_length=45, null=True)),
                ('place_loading_lod', models.CharField(blank=True, max_length=45, null=True)),
                ('loading_date_lod', models.DateField(blank=True, null=True)),
                ('place_dischande_lod', models.CharField(blank=True, max_length=45, null=True)),
                ('driver_lod', models.IntegerField(blank=True, null=True)),
                ('dispash_lod', models.IntegerField(blank=True, null=True)),
                ('value_lod', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('number_lod', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('paid_lod', models.IntegerField(blank=True, null=True)),
                ('note_lod', models.TextField(blank=True, null=True)),
                ('employees', models.ManyToManyField(to='accounting.Employees')),
                ('users_id_use', models.ForeignKey(db_column='USERS_id_use', on_delete=django.db.models.deletion.DO_NOTHING, to='administration.Users')),
            ],
        ),
        migrations.CreateModel(
            name='LoadsHasFee',
            fields=[
                ('id_lfe', models.AutoField(primary_key=True, serialize=False)),
                ('value_lfe', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('fee', models.ForeignKey(db_column='FEE_id_fee', on_delete=django.db.models.deletion.DO_NOTHING, to='accounting.Fee')),
                ('loads', models.ForeignKey(db_column='LOADS_id_lod', on_delete=django.db.models.deletion.DO_NOTHING, to='logistic.Loads')),
            ],
        ),
        migrations.CreateModel(
            name='PermissionsLogt',
            fields=[
                ('id_prm', models.AutoField(primary_key=True, serialize=False)),
                ('date_prm', models.DateField(blank=True, null=True)),
                ('usdot_prm', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('usdot_pin_prm', models.CharField(blank=True, max_length=20, null=True)),
                ('txdmv_prm', models.CharField(blank=True, max_length=20, null=True)),
                ('txdmv_user_prm', models.CharField(blank=True, max_length=20, null=True)),
                ('txdmv_passd_prm', models.CharField(blank=True, max_length=45, null=True)),
                ('txdmv_date_prm', models.DateField(blank=True, null=True)),
                ('txdmv_date_exp_prm', models.DateField(blank=True, null=True)),
                ('mc_prm', models.CharField(blank=True, max_length=20, null=True)),
                ('mc_pin_prm', models.CharField(blank=True, max_length=20, null=True)),
                ('boc3_prm', models.IntegerField(blank=True, null=True)),
                ('boc3_date_prm', models.DateField(blank=True, null=True)),
                ('ucr_prm', models.IntegerField(blank=True, null=True)),
                ('update_prm', models.DateField(blank=True, null=True)),
                ('users', models.ForeignKey(db_column='USERS_id_use', on_delete=django.db.models.deletion.DO_NOTHING, to='administration.Users')),
            ],
        ),
        migrations.CreateModel(
            name='TravelExpenses',
            fields=[
                ('id_tre', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('date_tre', models.DateField(blank=True, null=True)),
                ('value_tre', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('accounts', models.ForeignKey(db_column='ACCOUNTS_id_acn', on_delete=django.db.models.deletion.DO_NOTHING, to='accounting.Accounts')),
                ('employees', models.ForeignKey(db_column='EMPLOYEES_id_emp', on_delete=django.db.models.deletion.DO_NOTHING, to='accounting.Employees')),
                ('users', models.ForeignKey(db_column='USERS_id_use', on_delete=django.db.models.deletion.DO_NOTHING, to='administration.Users')),
            ],
        ),
        migrations.CreateModel(
            name='TrucksLogt',
            fields=[
                ('id_tuk', models.AutoField(primary_key=True, serialize=False)),
                ('type_tuk', models.CharField(blank=True, max_length=45, null=True)),
                ('year_tuk', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('model_tuk', models.CharField(blank=True, max_length=45, null=True)),
                ('serial_tuk', models.CharField(blank=True, max_length=20, null=True)),
                ('number_tuk', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('insp_date_exp_tuk', models.DateField(blank=True, null=True)),
                ('regit_date_exp_tuk', models.DateField(blank=True, null=True)),
                ('deactivate_tuk', models.IntegerField(blank=True, null=True)),
                ('deactivate_date_tuk', models.DateField(blank=True, null=True)),
                ('active_tuk', models.IntegerField()),
                ('date_deactivated_tuk', models.DateTimeField(blank=True, null=True)),
                ('users_id_use', models.ForeignKey(db_column='USERS_id_use', on_delete=django.db.models.deletion.DO_NOTHING, to='administration.Users')),
            ],
        ),
        migrations.AddField(
            model_name='invoiceshasloads',
            name='loads',
            field=models.ForeignKey(db_column='LOADS_id_lod', on_delete=django.db.models.deletion.DO_NOTHING, to='logistic.Loads'),
        ),
        migrations.AddField(
            model_name='iftalogt',
            name='trucks',
            field=models.ForeignKey(db_column='TRUCKS_id_tru', on_delete=django.db.models.deletion.DO_NOTHING, to='logistic.TrucksLogt'),
        ),
        migrations.AddField(
            model_name='iftalogt',
            name='users',
            field=models.ForeignKey(db_column='USERS_id_use', on_delete=django.db.models.deletion.DO_NOTHING, to='administration.Users'),
        ),
    ]
