# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 04:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriversLogt',
            fields=[
                ('id_dr', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('license_numb', models.CharField(blank=True, max_length=45, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('lic_date_exp', models.DateField(blank=True, null=True)),
                ('medicard_date_exp', models.DateField(blank=True, null=True)),
                ('drugtest_date', models.DateField(blank=True, null=True)),
                ('drugtest_date_exp', models.DateField(blank=True, null=True)),
                ('mbr_date', models.DateField(blank=True, null=True)),
                ('mbr_date_exp', models.DateField(blank=True, null=True)),
                ('begining_date', models.DateField(blank=True, null=True)),
                ('deactivate', models.IntegerField(blank=True, null=True)),
                ('deactivate_date', models.DateField(blank=True, null=True)),
                ('active', models.IntegerField()),
                ('date_deactivated', models.DateTimeField(blank=True, null=True)),
                ('users', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IftaLogt',
            fields=[
                ('id_ift', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=45, null=True)),
                ('milles', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('gallons', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('customers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Customers')),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceLogt',
            fields=[
                ('id_inr', models.AutoField(primary_key=True, serialize=False)),
                ('down_payment', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('pilicy_efective_date', models.DateField(blank=True, null=True)),
                ('pilicy_date_exp', models.DateField(blank=True, null=True)),
                ('liability', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('pilicy_liability', models.CharField(blank=True, max_length=45, null=True)),
                ('cargo', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('cargo_pilicy', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('physical_damage', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('physical_damg_pilicy', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('sale_type', models.CharField(blank=True, max_length=20, null=True)),
                ('sale_date_fee', models.DateField(blank=True, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('comision', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('paid', models.IntegerField(blank=True, null=True)),
                ('accounts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Accounts')),
                ('users', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvoicesHasLoads',
            fields=[
                ('id_inl', models.AutoField(primary_key=True, serialize=False)),
                ('invoices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Invoices')),
            ],
        ),
        migrations.CreateModel(
            name='Loads',
            fields=[
                ('id_lod', models.AutoField(primary_key=True, serialize=False)),
                ('broker', models.CharField(blank=True, max_length=45, null=True)),
                ('place_loading', models.CharField(blank=True, max_length=45, null=True)),
                ('loading_date', models.DateField(blank=True, null=True)),
                ('place_dischande', models.CharField(blank=True, max_length=45, null=True)),
                ('driver', models.IntegerField(blank=True, null=True)),
                ('dispash', models.IntegerField(blank=True, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('number', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('paid', models.IntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('employees', models.ManyToManyField(blank=True, to='accounting.Employees')),
                ('users', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoadsHasFee',
            fields=[
                ('id_lfe', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Fee')),
                ('loads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistic.Loads')),
            ],
        ),
        migrations.CreateModel(
            name='PermissionsLogt',
            fields=[
                ('id_prm', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('usdot', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('usdot_pin', models.CharField(blank=True, max_length=20, null=True)),
                ('txdmv', models.CharField(blank=True, max_length=20, null=True)),
                ('txdmv_user', models.CharField(blank=True, max_length=20, null=True)),
                ('txdmv_passd', models.CharField(blank=True, max_length=45, null=True)),
                ('txdmv_date', models.DateField(blank=True, null=True)),
                ('txdmv_date_exp', models.DateField(blank=True, null=True)),
                ('mc', models.CharField(blank=True, max_length=20, null=True)),
                ('mc_pin', models.CharField(blank=True, max_length=20, null=True)),
                ('boc3', models.IntegerField(blank=True, null=True)),
                ('boc3_date', models.DateField(blank=True, null=True)),
                ('ucr', models.IntegerField(blank=True, null=True)),
                ('update', models.DateField(blank=True, null=True)),
                ('users', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TravelExpenses',
            fields=[
                ('id_tre', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('accounts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Accounts')),
                ('employees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Employees')),
                ('users', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrucksLogt',
            fields=[
                ('id_tuk', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=45, null=True)),
                ('year', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('model', models.CharField(blank=True, max_length=45, null=True)),
                ('serial', models.CharField(blank=True, max_length=20, null=True)),
                ('number', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('insp_date_exp', models.DateField(blank=True, null=True)),
                ('regit_date_exp', models.DateField(blank=True, null=True)),
                ('deactivate', models.IntegerField(blank=True, null=True)),
                ('deactivate_date', models.DateField(blank=True, null=True)),
                ('active', models.IntegerField()),
                ('date_deactivated', models.DateTimeField(blank=True, null=True)),
                ('users', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='invoiceshasloads',
            name='loads',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistic.Loads'),
        ),
        migrations.AddField(
            model_name='iftalogt',
            name='trucks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistic.TrucksLogt'),
        ),
        migrations.AddField(
            model_name='iftalogt',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
