# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 23:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverslogt',
            name='users_id_use',
            field=models.ForeignKey(db_column='USERS_id_use', on_delete=django.db.models.deletion.CASCADE, to='administration.Users'),
        ),
        migrations.AlterField(
            model_name='iftalogt',
            name='customers',
            field=models.ForeignKey(db_column='CUSTOMERS_id_cut', on_delete=django.db.models.deletion.CASCADE, to='accounting.Customers'),
        ),
        migrations.AlterField(
            model_name='iftalogt',
            name='trucks',
            field=models.ForeignKey(db_column='TRUCKS_id_tru', on_delete=django.db.models.deletion.CASCADE, to='logistic.TrucksLogt'),
        ),
        migrations.AlterField(
            model_name='iftalogt',
            name='users',
            field=models.ForeignKey(db_column='USERS_id_use', on_delete=django.db.models.deletion.CASCADE, to='administration.Users'),
        ),
        migrations.AlterField(
            model_name='insurancelogt',
            name='accounts',
            field=models.ForeignKey(db_column='ACCOUNTS_id_acn', on_delete=django.db.models.deletion.CASCADE, to='accounting.Accounts'),
        ),
        migrations.AlterField(
            model_name='insurancelogt',
            name='users',
            field=models.ForeignKey(db_column='USERS_id_use', on_delete=django.db.models.deletion.CASCADE, to='administration.Users'),
        ),
        migrations.AlterField(
            model_name='invoiceshasloads',
            name='invoices',
            field=models.ForeignKey(db_column='INVOICES_id_inv', on_delete=django.db.models.deletion.CASCADE, to='accounting.Invoices'),
        ),
        migrations.AlterField(
            model_name='invoiceshasloads',
            name='loads',
            field=models.ForeignKey(db_column='LOADS_id_lod', on_delete=django.db.models.deletion.CASCADE, to='logistic.Loads'),
        ),
        migrations.AlterField(
            model_name='loads',
            name='employees',
            field=models.ManyToManyField(blank=True, to='accounting.Employees'),
        ),
        migrations.AlterField(
            model_name='loads',
            name='users_id_use',
            field=models.ForeignKey(db_column='USERS_id_use', on_delete=django.db.models.deletion.CASCADE, to='administration.Users'),
        ),
        migrations.AlterField(
            model_name='loadshasfee',
            name='fee',
            field=models.ForeignKey(db_column='FEE_id_fee', on_delete=django.db.models.deletion.CASCADE, to='accounting.Fee'),
        ),
        migrations.AlterField(
            model_name='loadshasfee',
            name='loads',
            field=models.ForeignKey(db_column='LOADS_id_lod', on_delete=django.db.models.deletion.CASCADE, to='logistic.Loads'),
        ),
        migrations.AlterField(
            model_name='permissionslogt',
            name='users',
            field=models.ForeignKey(db_column='USERS_id_use', on_delete=django.db.models.deletion.CASCADE, to='administration.Users'),
        ),
        migrations.AlterField(
            model_name='travelexpenses',
            name='accounts',
            field=models.ForeignKey(db_column='ACCOUNTS_id_acn', on_delete=django.db.models.deletion.CASCADE, to='accounting.Accounts'),
        ),
        migrations.AlterField(
            model_name='travelexpenses',
            name='employees',
            field=models.ForeignKey(db_column='EMPLOYEES_id_emp', on_delete=django.db.models.deletion.CASCADE, to='accounting.Employees'),
        ),
        migrations.AlterField(
            model_name='travelexpenses',
            name='users',
            field=models.ForeignKey(db_column='USERS_id_use', on_delete=django.db.models.deletion.CASCADE, to='administration.Users'),
        ),
        migrations.AlterField(
            model_name='truckslogt',
            name='users_id_use',
            field=models.ForeignKey(db_column='USERS_id_use', on_delete=django.db.models.deletion.CASCADE, to='administration.Users'),
        ),
    ]
