# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0002_auto_20170710_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverslogt',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='load',
            name='note',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
