# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-30 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0003_auto_20170723_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchlogt',
            name='comission',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='driverslogt',
            name='ssn',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='load',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
