# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-30 07:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_auto_20171230_0623'),
        ('logistic', '0004_auto_20171230_0623'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoicesLoadHasLoad',
            fields=[
                ('id_inl', models.AutoField(primary_key=True, serialize=False)),
                ('invoices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.InvoiceLoad')),
                ('loads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistic.Load')),
            ],
        ),
    ]
