# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 18:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id_acn', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('primary', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AccountDescrip',
            fields=[
                ('id_acd', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id_cut', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('lastname', models.CharField(blank=True, max_length=45, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('no_social', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('deactivated', models.BooleanField(default=False)),
                ('date_deactivated', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id_emp', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('lastname', models.CharField(blank=True, max_length=45, null=True)),
                ('adress', models.CharField(blank=True, max_length=255, null=True)),
                ('social_no', models.CharField(blank=True, max_length=20, null=True)),
                ('date_admis', models.DateField(blank=True, null=True)),
                ('phone', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('type_salary', models.CharField(blank=True, max_length=20, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('position', models.CharField(blank=True, max_length=20, null=True)),
                ('deactivated', models.BooleanField(default=False)),
                ('date_deactivated', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id_fee', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id_inv', models.AutoField(primary_key=True, serialize=False)),
                ('serial', models.IntegerField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('waytopay', models.CharField(blank=True, max_length=20, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('paid', models.BooleanField(default=True)),
                ('prefix', models.CharField(blank=True, max_length=4, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvoicesHasItem',
            fields=[
                ('id_ind', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_ind', models.IntegerField(blank=True, null=True)),
                ('value_ind', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id_ite', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id_rec', models.AutoField(primary_key=True, serialize=False)),
                ('serial', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(max_length=45)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weytopay', models.CharField(max_length=20)),
                ('paid', models.BooleanField(default=True)),
                ('accounts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id_sal', models.AutoField(primary_key=True, serialize=False)),
                ('start_date_sal', models.DateField(blank=True, null=True)),
                ('end_date_sal', models.DateField(blank=True, null=True)),
                ('serial_sal', models.CharField(blank=True, max_length=20, null=True)),
                ('discount_sal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('value_sal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('accounts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Account')),
                ('employees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Employee')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
