# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDescrip',
            fields=[
                ('id_acd', models.AutoField(primary_key=True, serialize=False)),
                ('date_acd', models.DateField()),
                ('value_acd', models.DecimalField(decimal_places=0, max_digits=10)),
                ('type_acd', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id_acn', models.AutoField(primary_key=True, serialize=False)),
                ('name_acn', models.CharField(max_length=20)),
                ('description_acn', models.CharField(blank=True, max_length=255, null=True)),
                ('primary_acn', models.IntegerField(blank=True, null=True)),
                ('accounts_id', models.ForeignKey(db_column='ACCOUNTS_id_acn', on_delete=django.db.models.deletion.DO_NOTHING, to='accounting.Accounts')),
                ('users', models.ForeignKey(db_column='USERS_id_use', on_delete=django.db.models.deletion.DO_NOTHING, to='administration.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id_cut', models.AutoField(primary_key=True, serialize=False)),
                ('name_cut', models.CharField(blank=True, max_length=20, null=True)),
                ('lastname_cut', models.CharField(blank=True, max_length=45, null=True)),
                ('address_cut', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_cut', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('no_social_cut', models.CharField(blank=True, max_length=20, null=True)),
                ('email_cut', models.CharField(blank=True, max_length=255, null=True)),
                ('business', models.ForeignKey(db_column='BUSINESS_id_bus', on_delete=django.db.models.deletion.DO_NOTHING, to='administration.Business')),
                ('folders', models.ForeignKey(db_column='FOLDERS_id_fld', on_delete=django.db.models.deletion.DO_NOTHING, to='administration.Folders')),
                ('users', models.ForeignKey(db_column='USERS_id_use', on_delete=django.db.models.deletion.DO_NOTHING, to='administration.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id_emp', models.AutoField(primary_key=True, serialize=False)),
                ('name_emp', models.CharField(blank=True, max_length=20, null=True)),
                ('lastname_emp', models.CharField(blank=True, max_length=45, null=True)),
                ('adress_emp', models.CharField(blank=True, max_length=255, null=True)),
                ('social_no_emp', models.CharField(blank=True, max_length=20, null=True)),
                ('date_admis_emp', models.DateField(blank=True, null=True)),
                ('phone_emp', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('email_emp', models.CharField(blank=True, max_length=255, null=True)),
                ('type_salary_emp', models.CharField(blank=True, max_length=20, null=True)),
                ('value_emp', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('position_emp', models.CharField(blank=True, max_length=20, null=True)),
                ('business', models.ForeignKey(db_column='BUSINESS_id_bus', on_delete=django.db.models.deletion.DO_NOTHING, to='administration.Business')),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id_fee', models.AutoField(primary_key=True, serialize=False)),
                ('description_fee', models.CharField(blank=True, max_length=255, null=True)),
                ('type_fee', models.CharField(blank=True, max_length=20, null=True)),
                ('value_fee', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('accounts', models.ForeignKey(db_column='ACCOUNTS_id_acn', on_delete=django.db.models.deletion.DO_NOTHING, to='accounting.Accounts')),
            ],
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id_inv', models.AutoField(primary_key=True, serialize=False)),
                ('serial_inv', models.IntegerField()),
                ('date_start_inv', models.DateField(blank=True, null=True)),
                ('subtotal_inv', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('start_date_inv', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('waytopay_inv', models.CharField(blank=True, max_length=20, null=True)),
                ('discount_inv', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('paid_inv', models.IntegerField(blank=True, null=True)),
                ('prefix_inv', models.CharField(blank=True, max_length=4, null=True)),
                ('end_date_inv', models.DateField(blank=True, null=True)),
                ('accounts', models.ForeignKey(db_column='ACCOUNTS_id_acn', on_delete=django.db.models.deletion.DO_NOTHING, to='accounting.Accounts')),
                ('business', models.ForeignKey(db_column='BUSINESS_id_bus', on_delete=django.db.models.deletion.DO_NOTHING, to='administration.Business')),
                ('customers', models.ForeignKey(db_column='CUSTOMERS_id_cut', on_delete=django.db.models.deletion.DO_NOTHING, to='accounting.Customers')),
                ('users', models.ForeignKey(db_column='USERS_id_use', on_delete=django.db.models.deletion.DO_NOTHING, to='administration.Users')),
            ],
        ),
        migrations.CreateModel(
            name='InvoicesHasItems',
            fields=[
                ('id_ind', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_ind', models.IntegerField(blank=True, null=True)),
                ('value_ind', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('invoices', models.ForeignKey(db_column='INVOICES_id_inv', on_delete=django.db.models.deletion.DO_NOTHING, to='accounting.Invoices')),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id_ite', models.AutoField(primary_key=True, serialize=False)),
                ('name_ite', models.CharField(blank=True, max_length=20, null=True)),
                ('description_ite', models.CharField(blank=True, max_length=255, null=True)),
                ('value_ite', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('accounts', models.ForeignKey(db_column='ACCOUNTS_id_acn', on_delete=django.db.models.deletion.DO_NOTHING, to='accounting.Accounts')),
            ],
        ),
        migrations.CreateModel(
            name='Receipts',
            fields=[
                ('id_rec', models.AutoField(primary_key=True, serialize=False)),
                ('serial_rec', models.CharField(max_length=20)),
                ('start_date_rec', models.DateField()),
                ('end_date_rec', models.DateField(blank=True, null=True)),
                ('description_rec', models.CharField(max_length=45)),
                ('subtotal_rec', models.DecimalField(decimal_places=0, max_digits=10)),
                ('total_rec', models.DecimalField(decimal_places=0, max_digits=10)),
                ('weytopay_rec', models.CharField(max_length=20)),
                ('paid_rec', models.IntegerField()),
                ('accounts', models.ForeignKey(db_column='ACCOUNTS_id_acn', on_delete=django.db.models.deletion.DO_NOTHING, to='accounting.Accounts')),
                ('business', models.ForeignKey(db_column='BUSINESS_id_bus', on_delete=django.db.models.deletion.DO_NOTHING, to='administration.Business')),
                ('users', models.ForeignKey(db_column='USERS_id_use', on_delete=django.db.models.deletion.DO_NOTHING, to='administration.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id_sal', models.AutoField(primary_key=True, serialize=False)),
                ('start_date_sal', models.DateField(blank=True, null=True)),
                ('end_date_sal', models.DateField(blank=True, null=True)),
                ('serial_sal', models.CharField(blank=True, max_length=20, null=True)),
                ('discount_sal', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('value_sal', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('accounts', models.ForeignKey(db_column='ACCOUNTS_id_acn', on_delete=django.db.models.deletion.DO_NOTHING, to='accounting.Accounts')),
                ('employees', models.ForeignKey(db_column='EMPLOYEES_id_emp', on_delete=django.db.models.deletion.DO_NOTHING, to='accounting.Employees')),
                ('users', models.ForeignKey(db_column='USERS_id_use', on_delete=django.db.models.deletion.DO_NOTHING, to='administration.Users')),
            ],
        ),
        migrations.AddField(
            model_name='invoiceshasitems',
            name='items',
            field=models.ForeignKey(db_column='ITEMS_id_ite', on_delete=django.db.models.deletion.DO_NOTHING, to='accounting.Items'),
        ),
        migrations.AddField(
            model_name='accountdescrip',
            name='accounts',
            field=models.ForeignKey(db_column='ACCOUNTS_id_acn', on_delete=django.db.models.deletion.DO_NOTHING, to='accounting.Accounts'),
        ),
        migrations.AddField(
            model_name='accountdescrip',
            name='users',
            field=models.ForeignKey(db_column='USERS_id_use', on_delete=django.db.models.deletion.DO_NOTHING, to='administration.Users'),
        ),
    ]
