# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='prefix',
            field=models.CharField(blank=True, default='inv', max_length=4, null=True),
        ),
    ]
