# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 04:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipts',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.Business'),
        ),
        migrations.AddField(
            model_name='receipts',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='items',
            name='accounts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Accounts'),
        ),
        migrations.AddField(
            model_name='invoiceshasitems',
            name='invoices',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Invoices'),
        ),
        migrations.AddField(
            model_name='invoiceshasitems',
            name='items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Items'),
        ),
        migrations.AddField(
            model_name='invoices',
            name='accounts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Accounts'),
        ),
        migrations.AddField(
            model_name='invoices',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.Business'),
        ),
        migrations.AddField(
            model_name='invoices',
            name='customers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Customers'),
        ),
        migrations.AddField(
            model_name='invoices',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fee',
            name='accounts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Accounts'),
        ),
        migrations.AddField(
            model_name='employees',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.Business'),
        ),
        migrations.AddField(
            model_name='customers',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.Business'),
        ),
        migrations.AddField(
            model_name='customers',
            name='folders',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.Folders'),
        ),
        migrations.AddField(
            model_name='customers',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accounts',
            name='accounts_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Accounts'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountdescrip',
            name='accounts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Accounts'),
        ),
        migrations.AddField(
            model_name='accountdescrip',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
