# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 23:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdescrip',
            name='accounts',
            field=models.ForeignKey(db_column='ACCOUNTS_id_acn', on_delete=django.db.models.deletion.CASCADE, to='accounting.Accounts'),
        ),
        migrations.AlterField(
            model_name='accountdescrip',
            name='users',
            field=models.ForeignKey(db_column='USERS_id_use', on_delete=django.db.models.deletion.CASCADE, to='administration.Users'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='accounts_id',
            field=models.ForeignKey(db_column='ACCOUNTS_id_acn', on_delete=django.db.models.deletion.CASCADE, to='accounting.Accounts'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='users',
            field=models.ForeignKey(db_column='USERS_id_use', on_delete=django.db.models.deletion.CASCADE, to='administration.Users'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='business',
            field=models.ForeignKey(db_column='BUSINESS_id_bus', on_delete=django.db.models.deletion.CASCADE, to='administration.Business'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='folders',
            field=models.ForeignKey(db_column='FOLDERS_id_fld', on_delete=django.db.models.deletion.CASCADE, to='administration.Folders'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='users',
            field=models.ForeignKey(db_column='USERS_id_use', on_delete=django.db.models.deletion.CASCADE, to='administration.Users'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='business',
            field=models.ForeignKey(db_column='BUSINESS_id_bus', on_delete=django.db.models.deletion.CASCADE, to='administration.Business'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='accounts',
            field=models.ForeignKey(db_column='ACCOUNTS_id_acn', on_delete=django.db.models.deletion.CASCADE, to='accounting.Accounts'),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='accounts',
            field=models.ForeignKey(db_column='ACCOUNTS_id_acn', on_delete=django.db.models.deletion.CASCADE, to='accounting.Accounts'),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='business',
            field=models.ForeignKey(db_column='BUSINESS_id_bus', on_delete=django.db.models.deletion.CASCADE, to='administration.Business'),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='customers',
            field=models.ForeignKey(db_column='CUSTOMERS_id_cut', on_delete=django.db.models.deletion.CASCADE, to='accounting.Customers'),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='users',
            field=models.ForeignKey(db_column='USERS_id_use', on_delete=django.db.models.deletion.CASCADE, to='administration.Users'),
        ),
        migrations.AlterField(
            model_name='invoiceshasitems',
            name='invoices',
            field=models.ForeignKey(db_column='INVOICES_id_inv', on_delete=django.db.models.deletion.CASCADE, to='accounting.Invoices'),
        ),
        migrations.AlterField(
            model_name='invoiceshasitems',
            name='items',
            field=models.ForeignKey(db_column='ITEMS_id_ite', on_delete=django.db.models.deletion.CASCADE, to='accounting.Items'),
        ),
        migrations.AlterField(
            model_name='items',
            name='accounts',
            field=models.ForeignKey(db_column='ACCOUNTS_id_acn', on_delete=django.db.models.deletion.CASCADE, to='accounting.Accounts'),
        ),
        migrations.AlterField(
            model_name='receipts',
            name='accounts',
            field=models.ForeignKey(db_column='ACCOUNTS_id_acn', on_delete=django.db.models.deletion.CASCADE, to='accounting.Accounts'),
        ),
        migrations.AlterField(
            model_name='receipts',
            name='business',
            field=models.ForeignKey(db_column='BUSINESS_id_bus', on_delete=django.db.models.deletion.CASCADE, to='administration.Business'),
        ),
        migrations.AlterField(
            model_name='receipts',
            name='users',
            field=models.ForeignKey(db_column='USERS_id_use', on_delete=django.db.models.deletion.CASCADE, to='administration.Users'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='accounts',
            field=models.ForeignKey(db_column='ACCOUNTS_id_acn', on_delete=django.db.models.deletion.CASCADE, to='accounting.Accounts'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='employees',
            field=models.ForeignKey(db_column='EMPLOYEES_id_emp', on_delete=django.db.models.deletion.CASCADE, to='accounting.Employees'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='users',
            field=models.ForeignKey(db_column='USERS_id_use', on_delete=django.db.models.deletion.CASCADE, to='administration.Users'),
        ),
    ]
