# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20170608_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='list_item',
            field=models.BooleanField(default=True),
        ),
    ]
