# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 06:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20170505_1807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountdescrip',
            old_name='date_acd',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='accountdescrip',
            old_name='type_acd',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='accountdescrip',
            old_name='value_acd',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='accounts',
            old_name='description_acn',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='accounts',
            old_name='name_acn',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='accounts',
            old_name='primary_acn',
            new_name='primary',
        ),
        migrations.RenameField(
            model_name='customers',
            old_name='address_cut',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='customers',
            old_name='email_cut',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='customers',
            old_name='lastname_cut',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='customers',
            old_name='name_cut',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='customers',
            old_name='no_social_cut',
            new_name='no_social',
        ),
        migrations.RenameField(
            model_name='customers',
            old_name='phone_cut',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='employees',
            old_name='adress_emp',
            new_name='adress',
        ),
        migrations.RenameField(
            model_name='employees',
            old_name='date_admis_emp',
            new_name='date_admis',
        ),
        migrations.RenameField(
            model_name='employees',
            old_name='email_emp',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='employees',
            old_name='lastname_emp',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='employees',
            old_name='name_emp',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='employees',
            old_name='phone_emp',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='employees',
            old_name='position_emp',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='employees',
            old_name='social_no_emp',
            new_name='social_no',
        ),
        migrations.RenameField(
            model_name='employees',
            old_name='type_salary_emp',
            new_name='type_salary',
        ),
        migrations.RenameField(
            model_name='employees',
            old_name='value_emp',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='fee',
            old_name='description_fee',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='fee',
            old_name='type_fee',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='fee',
            old_name='value_fee',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='invoices',
            old_name='date_start_inv',
            new_name='date_start',
        ),
        migrations.RenameField(
            model_name='invoices',
            old_name='discount_inv',
            new_name='discount',
        ),
        migrations.RenameField(
            model_name='invoices',
            old_name='end_date_inv',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='invoices',
            old_name='paid_inv',
            new_name='paid',
        ),
        migrations.RenameField(
            model_name='invoices',
            old_name='prefix_inv',
            new_name='prefix',
        ),
        migrations.RenameField(
            model_name='invoices',
            old_name='serial_inv',
            new_name='serial',
        ),
        migrations.RenameField(
            model_name='invoices',
            old_name='start_date_inv',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='invoices',
            old_name='subtotal_inv',
            new_name='subtotal',
        ),
        migrations.RenameField(
            model_name='invoices',
            old_name='waytopay_inv',
            new_name='waytopay',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='description_ite',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='name_ite',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='value_ite',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='receipts',
            old_name='description_rec',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='receipts',
            old_name='end_date_rec',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='receipts',
            old_name='paid_rec',
            new_name='paid',
        ),
        migrations.RenameField(
            model_name='receipts',
            old_name='serial_rec',
            new_name='serial',
        ),
        migrations.RenameField(
            model_name='receipts',
            old_name='start_date_rec',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='receipts',
            old_name='subtotal_rec',
            new_name='subtotal',
        ),
        migrations.RenameField(
            model_name='receipts',
            old_name='total_rec',
            new_name='total',
        ),
        migrations.RenameField(
            model_name='receipts',
            old_name='weytopay_rec',
            new_name='weytopay',
        ),
        migrations.AlterField(
            model_name='accountdescrip',
            name='accounts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Accounts'),
        ),
        migrations.AlterField(
            model_name='accountdescrip',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Users'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='accounts_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Accounts'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Users'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Business'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='folders',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Folders'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Users'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Business'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='accounts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Accounts'),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='accounts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Accounts'),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Business'),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='customers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Customers'),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Users'),
        ),
        migrations.AlterField(
            model_name='invoiceshasitems',
            name='invoices',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Invoices'),
        ),
        migrations.AlterField(
            model_name='invoiceshasitems',
            name='items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Items'),
        ),
        migrations.AlterField(
            model_name='items',
            name='accounts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Accounts'),
        ),
        migrations.AlterField(
            model_name='receipts',
            name='accounts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Accounts'),
        ),
        migrations.AlterField(
            model_name='receipts',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Business'),
        ),
        migrations.AlterField(
            model_name='receipts',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Users'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='accounts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Accounts'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='employees',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Employees'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Users'),
        ),
    ]
