# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20170531_0021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeehaspayment',
            old_name='employee',
            new_name='employ',
        ),
        migrations.AddField(
            model_name='accountdescrip',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
