# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20170517_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='comercial_name',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
