# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20170509_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='accounts_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Accounts'),
        ),
    ]
