# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_auto_20170601_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
