# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_employee_comercial_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdescrip',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
