# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 17:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_auto_20170518_1445'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Salary',
            new_name='Payment',
        ),
    ]
