# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_auto_20170723_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdescrip',
            name='waytopay',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
