# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-20 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_accountdescrip_waytopay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='prefix',
            field=models.CharField(default='inv', max_length=4),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='start_date',
            field=models.DateField(default='2017-08-20'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='waytopay',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='invoiceshasitem',
            name='description',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='invoiceshasitem',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='invoiceshasitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoiceshasitem',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='start_date',
            field=models.DateField(default='2017-08-20'),
        ),
    ]
