# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_auto_20170522_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdescrip',
            name='document',
            field=models.IntegerField(),
        ),
    ]
