# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 16:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_auto_20171111_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='comition_fee',
            new_name='comission_fee',
        ),
    ]
