# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-22 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_auto_20171021_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='start_date',
            field=models.DateField(default='2017-10-22'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='start_date',
            field=models.DateField(default='2017-10-22'),
        ),
    ]
