# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-30 06:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_auto_20171111_1615'),
        ('accounting', '0012_auto_20171022_1557'),
    ]

    operations = [
    ]
