# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-30 06:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0009_auto_20170805_1842'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0013_merge_20171230_0615')
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceLoad',
            fields=[
                ('id_inv', models.AutoField(primary_key=True, serialize=False)),
                ('biller', models.CharField(blank=True, max_length=45, null=True)),
                ('biller_address', models.CharField(blank=True, max_length=100, null=True)),
                ('biller_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('serial', models.IntegerField()),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('start_date', models.DateField(default='2017-12-30')),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('waytopay', models.CharField(max_length=20)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('comission_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('wire_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ach_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('prefix', models.CharField(default='inv', max_length=4)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.Busines')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='start_date',
            field=models.DateField(default='2017-12-30'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pay_date',
            field=models.DateField(blank=True, default='2017-12-30', null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='start_date',
            field=models.DateField(default='2017-12-30'),
        ),
    ]
