# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('id_alt', models.AutoField(primary_key=True, serialize=False)),
                ('users', models.IntegerField(db_column='USERS_id_use')),
                ('category_alt', models.CharField(max_length=20)),
                ('drescription_alt', models.CharField(max_length=255)),
                ('create_date_alt', models.DateField()),
                ('show_date_alt', models.DateField()),
                ('end_date_alt', models.DateField()),
                ('active_alt', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id_bus', models.AutoField(primary_key=True, serialize=False)),
                ('name_bus', models.CharField(max_length=45)),
                ('address_bus', models.CharField(max_length=255)),
                ('phone_bus', models.DecimalField(decimal_places=0, max_digits=10)),
                ('fax_bus', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('website_bus', models.CharField(blank=True, max_length=255, null=True)),
                ('logo_bus', models.CharField(max_length=255)),
                ('date_created_bus', models.DateField()),
                ('active_bus', models.IntegerField()),
                ('date_deactivated_bus', models.DateField(blank=True, null=True)),
                ('messager_bus', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id_cld', models.AutoField(primary_key=True, serialize=False)),
                ('title_cld', models.CharField(blank=True, max_length=20, null=True)),
                ('description_cld', models.CharField(blank=True, max_length=255, null=True)),
                ('date_cld', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Changerusers',
            fields=[
                ('id_chg', models.AutoField(primary_key=True, serialize=False)),
                ('name_chg', models.CharField(blank=True, max_length=20, null=True)),
                ('value_before_chg', models.CharField(blank=True, max_length=350, null=True)),
                ('value_after_chg', models.CharField(blank=True, max_length=350, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id_cht', models.AutoField(primary_key=True, serialize=False)),
                ('date_cht', models.DateTimeField()),
                ('messager_cht', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id_dir', models.AutoField(primary_key=True, serialize=False)),
                ('name_dir', models.CharField(blank=True, max_length=45, null=True)),
                ('phone_dir', models.CharField(blank=True, max_length=20, null=True)),
                ('email_dir', models.CharField(blank=True, max_length=255, null=True)),
                ('address_dir', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id_fil', models.AutoField(primary_key=True, serialize=False)),
                ('name_fil', models.CharField(blank=True, max_length=45, null=True)),
                ('drescription_fil', models.CharField(blank=True, max_length=255, null=True)),
                ('url_fil', models.CharField(blank=True, max_length=255, null=True)),
                ('date_save_fil', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Folders',
            fields=[
                ('id_fld', models.AutoField(primary_key=True, serialize=False)),
                ('name_fld', models.CharField(max_length=45)),
                ('description_fld', models.CharField(blank=True, max_length=255, null=True)),
                ('folders_id', models.ForeignKey(db_column='FOLDERS_id_fld', on_delete=django.db.models.deletion.DO_NOTHING, to='administration.Folders')),
            ],
        ),
        migrations.CreateModel(
            name='Histories',
            fields=[
                ('id_hst', models.AutoField(primary_key=True, serialize=False)),
                ('date_hst', models.DateTimeField()),
                ('acction_hst', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id_men', models.AutoField(primary_key=True, serialize=False)),
                ('name_men', models.CharField(max_length=20)),
                ('description_men', models.CharField(blank=True, max_length=255, null=True)),
                ('active_men', models.IntegerField(blank=True, null=True)),
                ('url_men', models.CharField(blank=True, max_length=45, null=True)),
                ('menus_id', models.ForeignKey(blank=True, db_column='MENUS_id_men', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administration.Menus')),
            ],
        ),
        migrations.CreateModel(
            name='Profilers',
            fields=[
                ('id_prf', models.AutoField(primary_key=True, serialize=False)),
                ('name_prf', models.CharField(max_length=20)),
                ('description_prf', models.CharField(blank=True, max_length=255, null=True)),
                ('active_prf', models.IntegerField()),
                ('date_deactivated_prf', models.DateField(blank=True, null=True)),
                ('menus', models.ManyToManyField(to='administration.Menus')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id_use', models.AutoField(primary_key=True, serialize=False)),
                ('name_use', models.CharField(max_length=20)),
                ('lastname_use', models.CharField(blank=True, max_length=45, null=True)),
                ('email_use', models.CharField(max_length=255)),
                ('password_use', models.CharField(max_length=255)),
                ('date_created_use', models.DateField()),
                ('active_use', models.IntegerField()),
                ('date_deactivated_use', models.DateTimeField(blank=True, null=True)),
                ('online_use', models.IntegerField(blank=True, null=True)),
                ('profilers', models.ForeignKey(db_column='PROFILERS_id_prf', on_delete=django.db.models.deletion.DO_NOTHING, to='administration.Profilers')),
            ],
        ),
        migrations.AddField(
            model_name='histories',
            name='users',
            field=models.ForeignKey(db_column='USERS_id_use', on_delete=django.db.models.deletion.DO_NOTHING, to='administration.Users'),
        ),
        migrations.AddField(
            model_name='files',
            name='folders',
            field=models.ForeignKey(db_column='FOLDERS_id_fld', on_delete=django.db.models.deletion.DO_NOTHING, to='administration.Folders'),
        ),
        migrations.AddField(
            model_name='files',
            name='users',
            field=models.ForeignKey(db_column='USERS_id_use', on_delete=django.db.models.deletion.DO_NOTHING, to='administration.Users'),
        ),
        migrations.AddField(
            model_name='directory',
            name='users',
            field=models.ForeignKey(db_column='USERS_id_use', on_delete=django.db.models.deletion.DO_NOTHING, to='administration.Users'),
        ),
        migrations.AddField(
            model_name='chat',
            name='users',
            field=models.ForeignKey(db_column='USERS_id_use', on_delete=django.db.models.deletion.DO_NOTHING, to='administration.Users'),
        ),
        migrations.AddField(
            model_name='changerusers',
            name='histories',
            field=models.ForeignKey(db_column='HISTORIES_id_hst', on_delete=django.db.models.deletion.DO_NOTHING, to='administration.Histories'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='users',
            field=models.ForeignKey(db_column='USERS_id_use', on_delete=django.db.models.deletion.DO_NOTHING, to='administration.Users'),
        ),
        migrations.AddField(
            model_name='alerts',
            name='profilers',
            field=models.ManyToManyField(to='administration.Profilers'),
        ),
    ]
