# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 06:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_auto_20170506_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerts',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Users'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Users'),
        ),
        migrations.AlterField(
            model_name='changerusers',
            name='histories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Histories'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Users'),
        ),
        migrations.AlterField(
            model_name='directory',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Users'),
        ),
        migrations.AlterField(
            model_name='files',
            name='folders',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Folders'),
        ),
        migrations.AlterField(
            model_name='files',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Users'),
        ),
        migrations.AlterField(
            model_name='folders',
            name='folders_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Folders'),
        ),
        migrations.AlterField(
            model_name='histories',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Users'),
        ),
        migrations.AlterField(
            model_name='menus',
            name='menus_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.Menus'),
        ),
        migrations.AlterField(
            model_name='users',
            name='profilers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Profilers'),
        ),
    ]
